# Generated by Django 4.1.7 on 2023-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_dt_troca_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dt_troca_senha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
