# Generated by Django 4.1.7 on 2023-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dat_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='dat_inicia_trab',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='justificar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
