# Generated by Django 4.1.7 on 2023-04-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('accounts', '0003_alter_users_dat_admissao_alter_users_dat_inicia_trab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='escala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.escala'),
        ),
    ]
