# Generated by Django 4.1.7 on 2023-03-26 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_dt_troca_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dt_troca_senha',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
